
/****************************************************************

   This file was created automatically by `FlexCat 2.16'
   from "//source/cAMIra.cd"

   using CatComp.sd 1.2 (24.09.1999)

   Do NOT edit by hand!

****************************************************************/

#ifndef cAMIra_STRINGS_H
#define cAMIra_STRINGS_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef  cAMIra_BASIC_CODE
#undef  cAMIra_BASIC
#undef  cAMIra_CODE
#define cAMIra_BASIC
#define cAMIra_CODE
#endif

#ifdef  cAMIra_BASIC
#undef  cAMIra_ARRAY
#undef  cAMIra_BLOCK
#define cAMIra_ARRAY
#define cAMIra_BLOCK
#endif

#ifdef  cAMIra_ARRAY
#undef  cAMIra_NUMBERS
#undef  cAMIra_STRINGS
#define cAMIra_NUMBERS
#define cAMIra_STRINGS
#endif

#ifdef  cAMIra_BLOCK
#undef  cAMIra_STRINGS
#define cAMIra_STRINGS
#endif


#ifdef cAMIra_CODE
#include <proto/locale.h>
extern struct Library *LocaleBase;
#endif

#ifdef cAMIra_NUMBERS

#define STR_CAMIRA_DESCRIPTION 0
#define STR_CAMIRA_TRANSLATION_BY 1
#define STR_MAINWINDOW_TITLE 2
#define STR_MAINWINDOW_RELEASE 3
#define STR_MAINWINDOW_RELEASE_KEY 4
#define STR_MAINWINDOW_RELEASE_HELP 5
#define STR_MAINMENU_PROJECT 6
#define STR_MAINMENU_ABOUT 7
#define STR_MAINMENU_ABOUT_KEY 8
#define STR_MAINMENU_ABOUTMUI 9
#define STR_MAINMENU_QUIT 10
#define STR_MAINMENU_QUIT_KEY 11
#define STR_MAINMENU_VIEW 12
#define STR_MAINMENU_LOGWINDOW 13
#define STR_MAINMENU_LOGWINDOW_KEY 14
#define STR_MAINMENU_SETTINGS 15
#define STR_MAINMENU_SOURCE 16
#define STR_MAINMENU_SOURCE_KEY 17
#define STR_MAINMENU_STAMP 18
#define STR_MAINMENU_STAMP_KEY 19
#define STR_MAINMENU_DISPLAY 20
#define STR_MAINMENU_DISPLAY_KEY 21
#define STR_MAINMENU_SCHEDULER 22
#define STR_MAINMENU_SCHEDULER_KEY 23
#define STR_MAINMENU_CAPTURE 24
#define STR_MAINMENU_CAPTURE_KEY 25
#define STR_MAINMENU_UPLOAD 26
#define STR_MAINMENU_UPLOAD_KEY 27
#define STR_MAINMENU_LOG 28
#define STR_MAINMENU_LOG_KEY 29
#define STR_MAINMENU_MUI 30
#define STR_ABOUTWINDOW_TITLE 31
#define STR_ABOUTWINDOW_OK 32
#define STR_ABOUTWINDOW_OK_KEY 33
#define STR_ABOUTWINDOW_OK_HELP 34
#define STR_LOGWINDOW_TITLE 35
#define STR_LOGWINDOW_CLOSE 36
#define STR_LOGWINDOW_CLOSE_KEY 37
#define STR_LOGWINDOW_CLOSE_HELP 38
#define STR_LOGWINDOW_FLUSH 39
#define STR_LOGWINDOW_FLUSH_KEY 40
#define STR_LOGWINDOW_FLUSH_HELP 41
#define STR_LOGWINDOW_SAVE 42
#define STR_LOGWINDOW_SAVE_KEY 43
#define STR_LOGWINDOW_SAVE_HELP 44
#define STR_SETTINGSWINDOW_TITLE 45
#define STR_SETTINGSWINDOW_OK 46
#define STR_SETTINGSWINDOW_OK_KEY 47
#define STR_SETTINGSWINDOW_OK_HELP 48
#define STR_SETTINGSWINDOW_CANCEL 49
#define STR_SETTINGSWINDOW_CANCEL_KEY 50
#define STR_SETTINGSWINDOW_CANCEL_HELP 51
#define STR_SETTINGSWINDOW_CATEGORYLIST_HELP 52
#define STR_SETTINGSWINDOW_SOURCE 53
#define STR_SETTINGSWINDOW_VHIDRIVER 54
#define STR_SETTINGSWINDOW_VHIDRIVER_KEY 55
#define STR_SETTINGSWINDOW_VHIDRIVER_HELP 56
#define STR_SETTINGSWINDOW_VHIINFO 57
#define STR_SETTINGSWINDOW_VHIINFO_TEMPLATE 58
#define STR_SETTINGSWINDOW_VHIINFO_EMPTY 59
#define STR_SETTINGSWINDOW_VHIINPUT 60
#define STR_SETTINGSWINDOW_VHIINPUT_KEY 61
#define STR_SETTINGSWINDOW_VHIINPUT_HELP 62
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT 63
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT_KEY 64
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT_HELP 65
#define STR_SETTINGSWINDOW_VHICOLOR 66
#define STR_SETTINGSWINDOW_VHICOLOR_KEY 67
#define STR_SETTINGSWINDOW_VHICOLOR_HELP 68
#define STR_SETTINGSWINDOW_VHIX1 69
#define STR_SETTINGSWINDOW_VHIX1_KEY 70
#define STR_SETTINGSWINDOW_VHIX1_HELP 71
#define STR_SETTINGSWINDOW_VHIY1 72
#define STR_SETTINGSWINDOW_VHIY1_KEY 73
#define STR_SETTINGSWINDOW_VHIY1_HELP 74
#define STR_SETTINGSWINDOW_VHIX2 75
#define STR_SETTINGSWINDOW_VHIX2_KEY 76
#define STR_SETTINGSWINDOW_VHIX2_HELP 77
#define STR_SETTINGSWINDOW_VHIY2 78
#define STR_SETTINGSWINDOW_VHIY2_KEY 79
#define STR_SETTINGSWINDOW_VHIY2_HELP 80
#define STR_SETTINGSWINDOW_VHIWIDTH 81
#define STR_SETTINGSWINDOW_VHIWIDTH_KEY 82
#define STR_SETTINGSWINDOW_VHIWIDTH_HELP 83
#define STR_SETTINGSWINDOW_VHIHEIGHT 84
#define STR_SETTINGSWINDOW_VHIHEIGHT_KEY 85
#define STR_SETTINGSWINDOW_VHIHEIGHT_HELP 86
#define STR_SETTINGSWINDOW_STAMP 87
#define STR_SETTINGSWINDOW_STAMPENABLE 88
#define STR_SETTINGSWINDOW_STAMPENABLE_KEY 89
#define STR_SETTINGSWINDOW_STAMPENABLE_HELP 90
#define STR_SETTINGSWINDOW_STAMPTEXT 91
#define STR_SETTINGSWINDOW_STAMPTEXT_KEY 92
#define STR_SETTINGSWINDOW_STAMPTEXT_HELP 93
#define STR_SETTINGSWINDOW_STAMPFONT 94
#define STR_SETTINGSWINDOW_STAMPFONT_KEY 95
#define STR_SETTINGSWINDOW_STAMPFONT_HELP 96
#define STR_SETTINGSWINDOW_STAMPX 97
#define STR_SETTINGSWINDOW_STAMPX_KEY 98
#define STR_SETTINGSWINDOW_STAMPX_HELP 99
#define STR_SETTINGSWINDOW_STAMPY 100
#define STR_SETTINGSWINDOW_STAMPY_KEY 101
#define STR_SETTINGSWINDOW_STAMPY_HELP 102
#define STR_SETTINGSWINDOW_DISPLAY 103
#define STR_SETTINGSWINDOW_DISPLAYENABLE 104
#define STR_SETTINGSWINDOW_DISPLAYENABLE_KEY 105
#define STR_SETTINGSWINDOW_DISPLAYENABLE_HELP 106
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL 107
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL_KEY 108
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL_HELP 109
#define STR_SETTINGSWINDOW_DISPLAYZOOM 110
#define STR_SETTINGSWINDOW_DISPLAYZOOM_KEY 111
#define STR_SETTINGSWINDOW_DISPLAYZOOM_HELP 112
#define STR_SETTINGSWINDOW_DISPLAYRATIO 113
#define STR_SETTINGSWINDOW_DISPLAYRATIO_KEY 114
#define STR_SETTINGSWINDOW_DISPLAYRATIO_HELP 115
#define STR_SETTINGSWINDOW_DISPLAYRATIOFREE 116
#define STR_SETTINGSWINDOW_DISPLAYRATIOKEEP 117
#define STR_SETTINGSWINDOW_SCHEDULER 118
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL 119
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL_KEY 120
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL_HELP 121
#define STR_SETTINGSWINDOW_CAPTURE 122
#define STR_SETTINGSWINDOW_CAPTUREENABLE 123
#define STR_SETTINGSWINDOW_CAPTUREENABLE_KEY 124
#define STR_SETTINGSWINDOW_CAPTUREENABLE_HELP 125
#define STR_SETTINGSWINDOW_CAPTUREDRAWER 126
#define STR_SETTINGSWINDOW_CAPTUREDRAWER_KEY 127
#define STR_SETTINGSWINDOW_CAPTUREDRAWER_HELP 128
#define STR_SETTINGSWINDOW_CAPTUREFILE 129
#define STR_SETTINGSWINDOW_CAPTUREFILE_KEY 130
#define STR_SETTINGSWINDOW_CAPTUREFILE_HELP 131
#define STR_SETTINGSWINDOW_CAPTUREFORMAT 132
#define STR_SETTINGSWINDOW_CAPTUREFORMAT_KEY 133
#define STR_SETTINGSWINDOW_CAPTUREFORMAT_HELP 134
#define STR_SETTINGSWINDOW_FORMAT_JPG 135
#define STR_SETTINGSWINDOW_FORMAT_PNG 136
#define STR_SETTINGSWINDOW_UPLOAD 137
#define STR_SETTINGSWINDOW_UPLOADENABLE 138
#define STR_SETTINGSWINDOW_UPLOADENABLE_KEY 139
#define STR_SETTINGSWINDOW_UPLOADENABLE_HELP 140
#define STR_SETTINGSWINDOW_UPLOADSERVER 141
#define STR_SETTINGSWINDOW_UPLOADSERVER_KEY 142
#define STR_SETTINGSWINDOW_UPLOADSERVER_HELP 143
#define STR_SETTINGSWINDOW_UPLOADPASSIVE 144
#define STR_SETTINGSWINDOW_UPLOADPASSIVE_KEY 145
#define STR_SETTINGSWINDOW_UPLOADPASSIVE_HELP 146
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT 147
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT_KEY 148
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT_HELP 149
#define STR_SETTINGSWINDOW_UPLOADUSER 150
#define STR_SETTINGSWINDOW_UPLOADUSER_KEY 151
#define STR_SETTINGSWINDOW_UPLOADUSER_HELP 152
#define STR_SETTINGSWINDOW_UPLOADPASSWORD 153
#define STR_SETTINGSWINDOW_UPLOADPASSWORD_KEY 154
#define STR_SETTINGSWINDOW_UPLOADPASSWORD_HELP 155
#define STR_SETTINGSWINDOW_UPLOADDRAWER 156
#define STR_SETTINGSWINDOW_UPLOADDRAWER_KEY 157
#define STR_SETTINGSWINDOW_UPLOADDRAWER_HELP 158
#define STR_SETTINGSWINDOW_UPLOADFILE 159
#define STR_SETTINGSWINDOW_UPLOADFILE_KEY 160
#define STR_SETTINGSWINDOW_UPLOADFILE_HELP 161
#define STR_SETTINGSWINDOW_UPLOADFORMAT 162
#define STR_SETTINGSWINDOW_UPLOADFORMAT_KEY 163
#define STR_SETTINGSWINDOW_UPLOADFORMAT_HELP 164
#define STR_SETTINGSWINDOW_LOG 165
#define STR_SETTINGSWINDOW_LOGLEVEL 166
#define STR_SETTINGSWINDOW_LOGLEVEL_KEY 167
#define STR_SETTINGSWINDOW_LOGLEVEL_HELP 168
#define STR_LOGLEVEL_OFF 169
#define STR_LOGLEVEL_FAILURE 170
#define STR_LOGLEVEL_ERROR 171
#define STR_LOGLEVEL_WARNING 172
#define STR_LOGLEVEL_INFO 173
#define STR_LOGLEVEL_DEBUG 174
#define STR_SPECIFIER_YEAR_HELP 175
#define STR_SPECIFIER_MONTH_HELP 176
#define STR_SPECIFIER_DAY_HELP 177
#define STR_SPECIFIER_HOUR_HELP 178
#define STR_SPECIFIER_MINUTE_HELP 179
#define STR_SPECIFIER_SECOND_HELP 180
#define STR_SPECIFIER_COUNTER_HELP 181
#define STR_PROGRESS_TOGGLE 182
#define STR_PROGRESS_TOGGLE_KEY 183
#define STR_PROGRESS_TOGGLE_HELP 184
#define STR_PROGRESS_CANCEL 185
#define STR_PROGRESS_CANCEL_KEY 186
#define STR_PROGRESS_CANCEL_HELP 187

#endif /* cAMIra_NUMBERS */


/****************************************************************************/


#ifdef cAMIra_STRINGS

#define STR_CAMIRA_DESCRIPTION_STR "simple webcam application"
#define STR_CAMIRA_TRANSLATION_BY_STR "English localisation by program author."
#define STR_MAINWINDOW_TITLE_STR "cAMIra"
#define STR_MAINWINDOW_RELEASE_STR "Release"
#define STR_MAINWINDOW_RELEASE_KEY_STR "r"
#define STR_MAINWINDOW_RELEASE_HELP_STR "Click here to capture the image seen in the display."
#define STR_MAINMENU_PROJECT_STR "Project"
#define STR_MAINMENU_ABOUT_STR "About ..."
#define STR_MAINMENU_ABOUT_KEY_STR "?"
#define STR_MAINMENU_ABOUTMUI_STR "About MUI ..."
#define STR_MAINMENU_QUIT_STR "Quit"
#define STR_MAINMENU_QUIT_KEY_STR "Q"
#define STR_MAINMENU_VIEW_STR "View"
#define STR_MAINMENU_LOGWINDOW_STR "Log Window ..."
#define STR_MAINMENU_LOGWINDOW_KEY_STR "G"
#define STR_MAINMENU_SETTINGS_STR "Settings"
#define STR_MAINMENU_SOURCE_STR "Source ..."
#define STR_MAINMENU_SOURCE_KEY_STR "O"
#define STR_MAINMENU_STAMP_STR "Stamp ..."
#define STR_MAINMENU_STAMP_KEY_STR "T"
#define STR_MAINMENU_DISPLAY_STR "Display ..."
#define STR_MAINMENU_DISPLAY_KEY_STR "D"
#define STR_MAINMENU_SCHEDULER_STR "Scheduler ..."
#define STR_MAINMENU_SCHEDULER_KEY_STR "S"
#define STR_MAINMENU_CAPTURE_STR "Capture ..."
#define STR_MAINMENU_CAPTURE_KEY_STR "C"
#define STR_MAINMENU_UPLOAD_STR "Upload ..."
#define STR_MAINMENU_UPLOAD_KEY_STR "U"
#define STR_MAINMENU_LOG_STR "Log ..."
#define STR_MAINMENU_LOG_KEY_STR "L"
#define STR_MAINMENU_MUI_STR "MUI ..."
#define STR_ABOUTWINDOW_TITLE_STR "cAMIra information"
#define STR_ABOUTWINDOW_OK_STR "Ok"
#define STR_ABOUTWINDOW_OK_KEY_STR "o"
#define STR_ABOUTWINDOW_OK_HELP_STR "Click here after reading the informations about cAMIra."
#define STR_LOGWINDOW_TITLE_STR "cAMIra log"
#define STR_LOGWINDOW_CLOSE_STR "Close"
#define STR_LOGWINDOW_CLOSE_KEY_STR "c"
#define STR_LOGWINDOW_CLOSE_HELP_STR "Click here to close the log window."
#define STR_LOGWINDOW_FLUSH_STR "Flush"
#define STR_LOGWINDOW_FLUSH_KEY_STR "f"
#define STR_LOGWINDOW_FLUSH_HELP_STR "Clicking here will remove all messages and there is no way to get them back."
#define STR_LOGWINDOW_SAVE_STR "Save"
#define STR_LOGWINDOW_SAVE_KEY_STR "s"
#define STR_LOGWINDOW_SAVE_HELP_STR "If the current messages shall be stored in a file, click here."
#define STR_SETTINGSWINDOW_TITLE_STR "cAMIra settings"
#define STR_SETTINGSWINDOW_OK_STR "Ok"
#define STR_SETTINGSWINDOW_OK_KEY_STR "o"
#define STR_SETTINGSWINDOW_OK_HELP_STR "After clicking here, the new setting values will be used."
#define STR_SETTINGSWINDOW_CANCEL_STR "Cancel"
#define STR_SETTINGSWINDOW_CANCEL_KEY_STR "c"
#define STR_SETTINGSWINDOW_CANCEL_HELP_STR "Use this button to discard changes and continue using the old setting values."
#define STR_SETTINGSWINDOW_CATEGORYLIST_HELP_STR "Choose the category to edit."
#define STR_SETTINGSWINDOW_SOURCE_STR "Source"
#define STR_SETTINGSWINDOW_VHIDRIVER_STR "Driver"
#define STR_SETTINGSWINDOW_VHIDRIVER_KEY_STR "d"
#define STR_SETTINGSWINDOW_VHIDRIVER_HELP_STR "Enter here the name of the VHI driver that shall be used."
#define STR_SETTINGSWINDOW_VHIINFO_STR "Info"
#define STR_SETTINGSWINDOW_VHIINFO_TEMPLATE_STR "%s %d.%d by %s\n%s %d.%d by %s"
#define STR_SETTINGSWINDOW_VHIINFO_EMPTY_STR "\n"
#define STR_SETTINGSWINDOW_VHIINPUT_STR "Input"
#define STR_SETTINGSWINDOW_VHIINPUT_KEY_STR "i"
#define STR_SETTINGSWINDOW_VHIINPUT_HELP_STR "Choose the video input from this list."
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT_STR "Format"
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT_KEY_STR "m"
#define STR_SETTINGSWINDOW_VHIVIDEOFORMAT_HELP_STR "Choose the video format from this list."
#define STR_SETTINGSWINDOW_VHICOLOR_STR "Color"
#define STR_SETTINGSWINDOW_VHICOLOR_KEY_STR "c"
#define STR_SETTINGSWINDOW_VHICOLOR_HELP_STR "Choose between color and grayscale mode."
#define STR_SETTINGSWINDOW_VHIX1_STR "X1"
#define STR_SETTINGSWINDOW_VHIX1_KEY_STR "x"
#define STR_SETTINGSWINDOW_VHIX1_HELP_STR "Adjust horizontal position of upper left corner of the capture area."
#define STR_SETTINGSWINDOW_VHIY1_STR "Y1"
#define STR_SETTINGSWINDOW_VHIY1_KEY_STR "1"
#define STR_SETTINGSWINDOW_VHIY1_HELP_STR "Adjust vertical position of upper left corner of the capture area."
#define STR_SETTINGSWINDOW_VHIX2_STR "X2"
#define STR_SETTINGSWINDOW_VHIX2_KEY_STR "2"
#define STR_SETTINGSWINDOW_VHIX2_HELP_STR "Adjust horizontal position of lower right corner of the capture area."
#define STR_SETTINGSWINDOW_VHIY2_STR "Y2"
#define STR_SETTINGSWINDOW_VHIY2_KEY_STR "y"
#define STR_SETTINGSWINDOW_VHIY2_HELP_STR "Adjust vertical position of lower right corner of the capture area."
#define STR_SETTINGSWINDOW_VHIWIDTH_STR "Width"
#define STR_SETTINGSWINDOW_VHIWIDTH_KEY_STR "w"
#define STR_SETTINGSWINDOW_VHIWIDTH_HELP_STR "Enter the width of the output image."
#define STR_SETTINGSWINDOW_VHIHEIGHT_STR "Height"
#define STR_SETTINGSWINDOW_VHIHEIGHT_KEY_STR "h"
#define STR_SETTINGSWINDOW_VHIHEIGHT_HELP_STR "Enter the height of the output image."
#define STR_SETTINGSWINDOW_STAMP_STR "Stamp"
#define STR_SETTINGSWINDOW_STAMPENABLE_STR "Enable"
#define STR_SETTINGSWINDOW_STAMPENABLE_KEY_STR "e"
#define STR_SETTINGSWINDOW_STAMPENABLE_HELP_STR "When this switch is enabled, a custom text is printed in the image."
#define STR_SETTINGSWINDOW_STAMPTEXT_STR "Text"
#define STR_SETTINGSWINDOW_STAMPTEXT_KEY_STR "t"
#define STR_SETTINGSWINDOW_STAMPTEXT_HELP_STR "This is the text that will be printed in the image.\nSeveral specifier are available from the popup that will be expanded before printing."
#define STR_SETTINGSWINDOW_STAMPFONT_STR "Font"
#define STR_SETTINGSWINDOW_STAMPFONT_KEY_STR "f"
#define STR_SETTINGSWINDOW_STAMPFONT_HELP_STR "Specify the font that will be used to draw the text in the image, e .g. topaz/8."
#define STR_SETTINGSWINDOW_STAMPX_STR "X"
#define STR_SETTINGSWINDOW_STAMPX_KEY_STR "x"
#define STR_SETTINGSWINDOW_STAMPX_HELP_STR "This will be the horizontal start position of the text."
#define STR_SETTINGSWINDOW_STAMPY_STR "Y"
#define STR_SETTINGSWINDOW_STAMPY_KEY_STR "y"
#define STR_SETTINGSWINDOW_STAMPY_HELP_STR "This will be the vertical start position of the text."
#define STR_SETTINGSWINDOW_DISPLAY_STR "Display"
#define STR_SETTINGSWINDOW_DISPLAYENABLE_STR "Enable"
#define STR_SETTINGSWINDOW_DISPLAYENABLE_KEY_STR "e"
#define STR_SETTINGSWINDOW_DISPLAYENABLE_HELP_STR "When this switch is enabled, periodically display updates are triggered."
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL_STR "Update [ms]"
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL_KEY_STR "u"
#define STR_SETTINGSWINDOW_DISPLAYINTERVAL_HELP_STR "After this time in ms a new image for display is requested from the video hardware.\nNote, the digitize process may take longer than the time entered here. 0 disables the display."
#define STR_SETTINGSWINDOW_DISPLAYZOOM_STR "Zoom [%]"
#define STR_SETTINGSWINDOW_DISPLAYZOOM_KEY_STR "z"
#define STR_SETTINGSWINDOW_DISPLAYZOOM_HELP_STR "Spezify the zoom factor in % for displaying the digitized image. A value of 0 means that the image shall always fit in the window."
#define STR_SETTINGSWINDOW_DISPLAYRATIO_STR "Ratio"
#define STR_SETTINGSWINDOW_DISPLAYRATIO_KEY_STR "r"
#define STR_SETTINGSWINDOW_DISPLAYRATIO_HELP_STR "If zoom is 0 this selection defines the aspect ratio while drawring the image."
#define STR_SETTINGSWINDOW_DISPLAYRATIOFREE_STR "free"
#define STR_SETTINGSWINDOW_DISPLAYRATIOKEEP_STR "keep"
#define STR_SETTINGSWINDOW_SCHEDULER_STR "Scheduler"
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL_STR "Interval [s]"
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL_KEY_STR "i"
#define STR_SETTINGSWINDOW_SCHEDULERINTERVAL_HELP_STR "The scheduler triggers capture and upload when enabled. Specify here the interval in s for this to happen."
#define STR_SETTINGSWINDOW_CAPTURE_STR "Capture"
#define STR_SETTINGSWINDOW_CAPTUREENABLE_STR "Enable"
#define STR_SETTINGSWINDOW_CAPTUREENABLE_KEY_STR "e"
#define STR_SETTINGSWINDOW_CAPTUREENABLE_HELP_STR "When this switch is enabled, the scheduler triggers storing of digitized images on disk."
#define STR_SETTINGSWINDOW_CAPTUREDRAWER_STR "Drawer"
#define STR_SETTINGSWINDOW_CAPTUREDRAWER_KEY_STR "d"
#define STR_SETTINGSWINDOW_CAPTUREDRAWER_HELP_STR "This is the local base drawer for storing images. If it does not exist, capture will fail."
#define STR_SETTINGSWINDOW_CAPTUREFILE_STR "File"
#define STR_SETTINGSWINDOW_CAPTUREFILE_KEY_STR "f"
#define STR_SETTINGSWINDOW_CAPTUREFILE_HELP_STR "Enter here sub-path including the filename.\nSeveral specifiers can be used from the popup that get expanded to the final path.\nA filename extension based on the image format will be added automatically."
#define STR_SETTINGSWINDOW_CAPTUREFORMAT_STR "Format"
#define STR_SETTINGSWINDOW_CAPTUREFORMAT_KEY_STR "m"
#define STR_SETTINGSWINDOW_CAPTUREFORMAT_HELP_STR "Choose here one of the supported capture formats."
#define STR_SETTINGSWINDOW_FORMAT_JPG_STR "JPG"
#define STR_SETTINGSWINDOW_FORMAT_PNG_STR "PNG"
#define STR_SETTINGSWINDOW_UPLOAD_STR "Upload"
#define STR_SETTINGSWINDOW_UPLOADENABLE_STR "Enable"
#define STR_SETTINGSWINDOW_UPLOADENABLE_KEY_STR "e"
#define STR_SETTINGSWINDOW_UPLOADENABLE_HELP_STR "When this switch is enabled, the scheduler triggers uploading of digitized images to a FTP server."
#define STR_SETTINGSWINDOW_UPLOADSERVER_STR "Server"
#define STR_SETTINGSWINDOW_UPLOADSERVER_KEY_STR "s"
#define STR_SETTINGSWINDOW_UPLOADSERVER_HELP_STR "Enter here the server name."
#define STR_SETTINGSWINDOW_UPLOADPASSIVE_STR "Passive"
#define STR_SETTINGSWINDOW_UPLOADPASSIVE_KEY_STR "p"
#define STR_SETTINGSWINDOW_UPLOADPASSIVE_HELP_STR "When this switch is enabled, the passive transfer mode is used. When disabled, active mode is used."
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT_STR "Timeout [s]"
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT_KEY_STR "t"
#define STR_SETTINGSWINDOW_UPLOADTIMEOUT_HELP_STR "After that time in seconds of no server activity the connection will be canceled causing the upload to fail."
#define STR_SETTINGSWINDOW_UPLOADUSER_STR "User"
#define STR_SETTINGSWINDOW_UPLOADUSER_KEY_STR "u"
#define STR_SETTINGSWINDOW_UPLOADUSER_HELP_STR "Enter a user name, when using a personal account on the FTP server."
#define STR_SETTINGSWINDOW_UPLOADPASSWORD_STR "Password"
#define STR_SETTINGSWINDOW_UPLOADPASSWORD_KEY_STR "w"
#define STR_SETTINGSWINDOW_UPLOADPASSWORD_HELP_STR "If your account requires a password, enter it here. Note, the password is stored in plain text so far."
#define STR_SETTINGSWINDOW_UPLOADDRAWER_STR "Drawer"
#define STR_SETTINGSWINDOW_UPLOADDRAWER_KEY_STR "d"
#define STR_SETTINGSWINDOW_UPLOADDRAWER_HELP_STR "Specify the remote drawer to that the image shall be upladed.\nA filename extension based on the image format will be added automatically."
#define STR_SETTINGSWINDOW_UPLOADFILE_STR "File"
#define STR_SETTINGSWINDOW_UPLOADFILE_KEY_STR "f"
#define STR_SETTINGSWINDOW_UPLOADFILE_HELP_STR "Specify the remote filename to that the image shall be uploaded."
#define STR_SETTINGSWINDOW_UPLOADFORMAT_STR "Format"
#define STR_SETTINGSWINDOW_UPLOADFORMAT_KEY_STR "m"
#define STR_SETTINGSWINDOW_UPLOADFORMAT_HELP_STR "Choose here one of the supported upload formats."
#define STR_SETTINGSWINDOW_LOG_STR "Log"
#define STR_SETTINGSWINDOW_LOGLEVEL_STR "Level"
#define STR_SETTINGSWINDOW_LOGLEVEL_KEY_STR "l"
#define STR_SETTINGSWINDOW_LOGLEVEL_HELP_STR "Choose here up to what level messages shall be added to the log."
#define STR_LOGLEVEL_OFF_STR "off"
#define STR_LOGLEVEL_FAILURE_STR "failure"
#define STR_LOGLEVEL_ERROR_STR "error"
#define STR_LOGLEVEL_WARNING_STR "warning"
#define STR_LOGLEVEL_INFO_STR "info"
#define STR_LOGLEVEL_DEBUG_STR "debug"
#define STR_SPECIFIER_YEAR_HELP_STR "Year"
#define STR_SPECIFIER_MONTH_HELP_STR "Month as a decimal number (01-12)"
#define STR_SPECIFIER_DAY_HELP_STR "Day of the month, zero-padded (01-31)"
#define STR_SPECIFIER_HOUR_HELP_STR "Hour in 24h format (00-23)"
#define STR_SPECIFIER_MINUTE_HELP_STR "Minute (00-59)"
#define STR_SPECIFIER_SECOND_HELP_STR "Second (00-59)"
#define STR_SPECIFIER_COUNTER_HELP_STR "cAMIra counter (0000-9999)"
#define STR_PROGRESS_TOGGLE_STR "T"
#define STR_PROGRESS_TOGGLE_KEY_STR "t"
#define STR_PROGRESS_TOGGLE_HELP_STR "Toggling the button will suspend the current process until the button is toggled again."
#define STR_PROGRESS_CANCEL_STR "X"
#define STR_PROGRESS_CANCEL_KEY_STR "x"
#define STR_PROGRESS_CANCEL_HELP_STR "Pressing the button will cancel the current process."

#endif /* cAMIra_STRINGS */


/****************************************************************************/


#ifdef cAMIra_ARRAY

struct cAMIra_ArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct cAMIra_ArrayType cAMIra_Array[] =
{
    { STR_CAMIRA_DESCRIPTION, (STRPTR)STR_CAMIRA_DESCRIPTION_STR },
    { STR_CAMIRA_TRANSLATION_BY, (STRPTR)STR_CAMIRA_TRANSLATION_BY_STR },
    { STR_MAINWINDOW_TITLE, (STRPTR)STR_MAINWINDOW_TITLE_STR },
    { STR_MAINWINDOW_RELEASE, (STRPTR)STR_MAINWINDOW_RELEASE_STR },
    { STR_MAINWINDOW_RELEASE_KEY, (STRPTR)STR_MAINWINDOW_RELEASE_KEY_STR },
    { STR_MAINWINDOW_RELEASE_HELP, (STRPTR)STR_MAINWINDOW_RELEASE_HELP_STR },
    { STR_MAINMENU_PROJECT, (STRPTR)STR_MAINMENU_PROJECT_STR },
    { STR_MAINMENU_ABOUT, (STRPTR)STR_MAINMENU_ABOUT_STR },
    { STR_MAINMENU_ABOUT_KEY, (STRPTR)STR_MAINMENU_ABOUT_KEY_STR },
    { STR_MAINMENU_ABOUTMUI, (STRPTR)STR_MAINMENU_ABOUTMUI_STR },
    { STR_MAINMENU_QUIT, (STRPTR)STR_MAINMENU_QUIT_STR },
    { STR_MAINMENU_QUIT_KEY, (STRPTR)STR_MAINMENU_QUIT_KEY_STR },
    { STR_MAINMENU_VIEW, (STRPTR)STR_MAINMENU_VIEW_STR },
    { STR_MAINMENU_LOGWINDOW, (STRPTR)STR_MAINMENU_LOGWINDOW_STR },
    { STR_MAINMENU_LOGWINDOW_KEY, (STRPTR)STR_MAINMENU_LOGWINDOW_KEY_STR },
    { STR_MAINMENU_SETTINGS, (STRPTR)STR_MAINMENU_SETTINGS_STR },
    { STR_MAINMENU_SOURCE, (STRPTR)STR_MAINMENU_SOURCE_STR },
    { STR_MAINMENU_SOURCE_KEY, (STRPTR)STR_MAINMENU_SOURCE_KEY_STR },
    { STR_MAINMENU_STAMP, (STRPTR)STR_MAINMENU_STAMP_STR },
    { STR_MAINMENU_STAMP_KEY, (STRPTR)STR_MAINMENU_STAMP_KEY_STR },
    { STR_MAINMENU_DISPLAY, (STRPTR)STR_MAINMENU_DISPLAY_STR },
    { STR_MAINMENU_DISPLAY_KEY, (STRPTR)STR_MAINMENU_DISPLAY_KEY_STR },
    { STR_MAINMENU_SCHEDULER, (STRPTR)STR_MAINMENU_SCHEDULER_STR },
    { STR_MAINMENU_SCHEDULER_KEY, (STRPTR)STR_MAINMENU_SCHEDULER_KEY_STR },
    { STR_MAINMENU_CAPTURE, (STRPTR)STR_MAINMENU_CAPTURE_STR },
    { STR_MAINMENU_CAPTURE_KEY, (STRPTR)STR_MAINMENU_CAPTURE_KEY_STR },
    { STR_MAINMENU_UPLOAD, (STRPTR)STR_MAINMENU_UPLOAD_STR },
    { STR_MAINMENU_UPLOAD_KEY, (STRPTR)STR_MAINMENU_UPLOAD_KEY_STR },
    { STR_MAINMENU_LOG, (STRPTR)STR_MAINMENU_LOG_STR },
    { STR_MAINMENU_LOG_KEY, (STRPTR)STR_MAINMENU_LOG_KEY_STR },
    { STR_MAINMENU_MUI, (STRPTR)STR_MAINMENU_MUI_STR },
    { STR_ABOUTWINDOW_TITLE, (STRPTR)STR_ABOUTWINDOW_TITLE_STR },
    { STR_ABOUTWINDOW_OK, (STRPTR)STR_ABOUTWINDOW_OK_STR },
    { STR_ABOUTWINDOW_OK_KEY, (STRPTR)STR_ABOUTWINDOW_OK_KEY_STR },
    { STR_ABOUTWINDOW_OK_HELP, (STRPTR)STR_ABOUTWINDOW_OK_HELP_STR },
    { STR_LOGWINDOW_TITLE, (STRPTR)STR_LOGWINDOW_TITLE_STR },
    { STR_LOGWINDOW_CLOSE, (STRPTR)STR_LOGWINDOW_CLOSE_STR },
    { STR_LOGWINDOW_CLOSE_KEY, (STRPTR)STR_LOGWINDOW_CLOSE_KEY_STR },
    { STR_LOGWINDOW_CLOSE_HELP, (STRPTR)STR_LOGWINDOW_CLOSE_HELP_STR },
    { STR_LOGWINDOW_FLUSH, (STRPTR)STR_LOGWINDOW_FLUSH_STR },
    { STR_LOGWINDOW_FLUSH_KEY, (STRPTR)STR_LOGWINDOW_FLUSH_KEY_STR },
    { STR_LOGWINDOW_FLUSH_HELP, (STRPTR)STR_LOGWINDOW_FLUSH_HELP_STR },
    { STR_LOGWINDOW_SAVE, (STRPTR)STR_LOGWINDOW_SAVE_STR },
    { STR_LOGWINDOW_SAVE_KEY, (STRPTR)STR_LOGWINDOW_SAVE_KEY_STR },
    { STR_LOGWINDOW_SAVE_HELP, (STRPTR)STR_LOGWINDOW_SAVE_HELP_STR },
    { STR_SETTINGSWINDOW_TITLE, (STRPTR)STR_SETTINGSWINDOW_TITLE_STR },
    { STR_SETTINGSWINDOW_OK, (STRPTR)STR_SETTINGSWINDOW_OK_STR },
    { STR_SETTINGSWINDOW_OK_KEY, (STRPTR)STR_SETTINGSWINDOW_OK_KEY_STR },
    { STR_SETTINGSWINDOW_OK_HELP, (STRPTR)STR_SETTINGSWINDOW_OK_HELP_STR },
    { STR_SETTINGSWINDOW_CANCEL, (STRPTR)STR_SETTINGSWINDOW_CANCEL_STR },
    { STR_SETTINGSWINDOW_CANCEL_KEY, (STRPTR)STR_SETTINGSWINDOW_CANCEL_KEY_STR },
    { STR_SETTINGSWINDOW_CANCEL_HELP, (STRPTR)STR_SETTINGSWINDOW_CANCEL_HELP_STR },
    { STR_SETTINGSWINDOW_CATEGORYLIST_HELP, (STRPTR)STR_SETTINGSWINDOW_CATEGORYLIST_HELP_STR },
    { STR_SETTINGSWINDOW_SOURCE, (STRPTR)STR_SETTINGSWINDOW_SOURCE_STR },
    { STR_SETTINGSWINDOW_VHIDRIVER, (STRPTR)STR_SETTINGSWINDOW_VHIDRIVER_STR },
    { STR_SETTINGSWINDOW_VHIDRIVER_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIDRIVER_KEY_STR },
    { STR_SETTINGSWINDOW_VHIDRIVER_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIDRIVER_HELP_STR },
    { STR_SETTINGSWINDOW_VHIINFO, (STRPTR)STR_SETTINGSWINDOW_VHIINFO_STR },
    { STR_SETTINGSWINDOW_VHIINFO_TEMPLATE, (STRPTR)STR_SETTINGSWINDOW_VHIINFO_TEMPLATE_STR },
    { STR_SETTINGSWINDOW_VHIINFO_EMPTY, (STRPTR)STR_SETTINGSWINDOW_VHIINFO_EMPTY_STR },
    { STR_SETTINGSWINDOW_VHIINPUT, (STRPTR)STR_SETTINGSWINDOW_VHIINPUT_STR },
    { STR_SETTINGSWINDOW_VHIINPUT_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIINPUT_KEY_STR },
    { STR_SETTINGSWINDOW_VHIINPUT_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIINPUT_HELP_STR },
    { STR_SETTINGSWINDOW_VHIVIDEOFORMAT, (STRPTR)STR_SETTINGSWINDOW_VHIVIDEOFORMAT_STR },
    { STR_SETTINGSWINDOW_VHIVIDEOFORMAT_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIVIDEOFORMAT_KEY_STR },
    { STR_SETTINGSWINDOW_VHIVIDEOFORMAT_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIVIDEOFORMAT_HELP_STR },
    { STR_SETTINGSWINDOW_VHICOLOR, (STRPTR)STR_SETTINGSWINDOW_VHICOLOR_STR },
    { STR_SETTINGSWINDOW_VHICOLOR_KEY, (STRPTR)STR_SETTINGSWINDOW_VHICOLOR_KEY_STR },
    { STR_SETTINGSWINDOW_VHICOLOR_HELP, (STRPTR)STR_SETTINGSWINDOW_VHICOLOR_HELP_STR },
    { STR_SETTINGSWINDOW_VHIX1, (STRPTR)STR_SETTINGSWINDOW_VHIX1_STR },
    { STR_SETTINGSWINDOW_VHIX1_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIX1_KEY_STR },
    { STR_SETTINGSWINDOW_VHIX1_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIX1_HELP_STR },
    { STR_SETTINGSWINDOW_VHIY1, (STRPTR)STR_SETTINGSWINDOW_VHIY1_STR },
    { STR_SETTINGSWINDOW_VHIY1_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIY1_KEY_STR },
    { STR_SETTINGSWINDOW_VHIY1_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIY1_HELP_STR },
    { STR_SETTINGSWINDOW_VHIX2, (STRPTR)STR_SETTINGSWINDOW_VHIX2_STR },
    { STR_SETTINGSWINDOW_VHIX2_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIX2_KEY_STR },
    { STR_SETTINGSWINDOW_VHIX2_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIX2_HELP_STR },
    { STR_SETTINGSWINDOW_VHIY2, (STRPTR)STR_SETTINGSWINDOW_VHIY2_STR },
    { STR_SETTINGSWINDOW_VHIY2_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIY2_KEY_STR },
    { STR_SETTINGSWINDOW_VHIY2_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIY2_HELP_STR },
    { STR_SETTINGSWINDOW_VHIWIDTH, (STRPTR)STR_SETTINGSWINDOW_VHIWIDTH_STR },
    { STR_SETTINGSWINDOW_VHIWIDTH_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIWIDTH_KEY_STR },
    { STR_SETTINGSWINDOW_VHIWIDTH_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIWIDTH_HELP_STR },
    { STR_SETTINGSWINDOW_VHIHEIGHT, (STRPTR)STR_SETTINGSWINDOW_VHIHEIGHT_STR },
    { STR_SETTINGSWINDOW_VHIHEIGHT_KEY, (STRPTR)STR_SETTINGSWINDOW_VHIHEIGHT_KEY_STR },
    { STR_SETTINGSWINDOW_VHIHEIGHT_HELP, (STRPTR)STR_SETTINGSWINDOW_VHIHEIGHT_HELP_STR },
    { STR_SETTINGSWINDOW_STAMP, (STRPTR)STR_SETTINGSWINDOW_STAMP_STR },
    { STR_SETTINGSWINDOW_STAMPENABLE, (STRPTR)STR_SETTINGSWINDOW_STAMPENABLE_STR },
    { STR_SETTINGSWINDOW_STAMPENABLE_KEY, (STRPTR)STR_SETTINGSWINDOW_STAMPENABLE_KEY_STR },
    { STR_SETTINGSWINDOW_STAMPENABLE_HELP, (STRPTR)STR_SETTINGSWINDOW_STAMPENABLE_HELP_STR },
    { STR_SETTINGSWINDOW_STAMPTEXT, (STRPTR)STR_SETTINGSWINDOW_STAMPTEXT_STR },
    { STR_SETTINGSWINDOW_STAMPTEXT_KEY, (STRPTR)STR_SETTINGSWINDOW_STAMPTEXT_KEY_STR },
    { STR_SETTINGSWINDOW_STAMPTEXT_HELP, (STRPTR)STR_SETTINGSWINDOW_STAMPTEXT_HELP_STR },
    { STR_SETTINGSWINDOW_STAMPFONT, (STRPTR)STR_SETTINGSWINDOW_STAMPFONT_STR },
    { STR_SETTINGSWINDOW_STAMPFONT_KEY, (STRPTR)STR_SETTINGSWINDOW_STAMPFONT_KEY_STR },
    { STR_SETTINGSWINDOW_STAMPFONT_HELP, (STRPTR)STR_SETTINGSWINDOW_STAMPFONT_HELP_STR },
    { STR_SETTINGSWINDOW_STAMPX, (STRPTR)STR_SETTINGSWINDOW_STAMPX_STR },
    { STR_SETTINGSWINDOW_STAMPX_KEY, (STRPTR)STR_SETTINGSWINDOW_STAMPX_KEY_STR },
    { STR_SETTINGSWINDOW_STAMPX_HELP, (STRPTR)STR_SETTINGSWINDOW_STAMPX_HELP_STR },
    { STR_SETTINGSWINDOW_STAMPY, (STRPTR)STR_SETTINGSWINDOW_STAMPY_STR },
    { STR_SETTINGSWINDOW_STAMPY_KEY, (STRPTR)STR_SETTINGSWINDOW_STAMPY_KEY_STR },
    { STR_SETTINGSWINDOW_STAMPY_HELP, (STRPTR)STR_SETTINGSWINDOW_STAMPY_HELP_STR },
    { STR_SETTINGSWINDOW_DISPLAY, (STRPTR)STR_SETTINGSWINDOW_DISPLAY_STR },
    { STR_SETTINGSWINDOW_DISPLAYENABLE, (STRPTR)STR_SETTINGSWINDOW_DISPLAYENABLE_STR },
    { STR_SETTINGSWINDOW_DISPLAYENABLE_KEY, (STRPTR)STR_SETTINGSWINDOW_DISPLAYENABLE_KEY_STR },
    { STR_SETTINGSWINDOW_DISPLAYENABLE_HELP, (STRPTR)STR_SETTINGSWINDOW_DISPLAYENABLE_HELP_STR },
    { STR_SETTINGSWINDOW_DISPLAYINTERVAL, (STRPTR)STR_SETTINGSWINDOW_DISPLAYINTERVAL_STR },
    { STR_SETTINGSWINDOW_DISPLAYINTERVAL_KEY, (STRPTR)STR_SETTINGSWINDOW_DISPLAYINTERVAL_KEY_STR },
    { STR_SETTINGSWINDOW_DISPLAYINTERVAL_HELP, (STRPTR)STR_SETTINGSWINDOW_DISPLAYINTERVAL_HELP_STR },
    { STR_SETTINGSWINDOW_DISPLAYZOOM, (STRPTR)STR_SETTINGSWINDOW_DISPLAYZOOM_STR },
    { STR_SETTINGSWINDOW_DISPLAYZOOM_KEY, (STRPTR)STR_SETTINGSWINDOW_DISPLAYZOOM_KEY_STR },
    { STR_SETTINGSWINDOW_DISPLAYZOOM_HELP, (STRPTR)STR_SETTINGSWINDOW_DISPLAYZOOM_HELP_STR },
    { STR_SETTINGSWINDOW_DISPLAYRATIO, (STRPTR)STR_SETTINGSWINDOW_DISPLAYRATIO_STR },
    { STR_SETTINGSWINDOW_DISPLAYRATIO_KEY, (STRPTR)STR_SETTINGSWINDOW_DISPLAYRATIO_KEY_STR },
    { STR_SETTINGSWINDOW_DISPLAYRATIO_HELP, (STRPTR)STR_SETTINGSWINDOW_DISPLAYRATIO_HELP_STR },
    { STR_SETTINGSWINDOW_DISPLAYRATIOFREE, (STRPTR)STR_SETTINGSWINDOW_DISPLAYRATIOFREE_STR },
    { STR_SETTINGSWINDOW_DISPLAYRATIOKEEP, (STRPTR)STR_SETTINGSWINDOW_DISPLAYRATIOKEEP_STR },
    { STR_SETTINGSWINDOW_SCHEDULER, (STRPTR)STR_SETTINGSWINDOW_SCHEDULER_STR },
    { STR_SETTINGSWINDOW_SCHEDULERINTERVAL, (STRPTR)STR_SETTINGSWINDOW_SCHEDULERINTERVAL_STR },
    { STR_SETTINGSWINDOW_SCHEDULERINTERVAL_KEY, (STRPTR)STR_SETTINGSWINDOW_SCHEDULERINTERVAL_KEY_STR },
    { STR_SETTINGSWINDOW_SCHEDULERINTERVAL_HELP, (STRPTR)STR_SETTINGSWINDOW_SCHEDULERINTERVAL_HELP_STR },
    { STR_SETTINGSWINDOW_CAPTURE, (STRPTR)STR_SETTINGSWINDOW_CAPTURE_STR },
    { STR_SETTINGSWINDOW_CAPTUREENABLE, (STRPTR)STR_SETTINGSWINDOW_CAPTUREENABLE_STR },
    { STR_SETTINGSWINDOW_CAPTUREENABLE_KEY, (STRPTR)STR_SETTINGSWINDOW_CAPTUREENABLE_KEY_STR },
    { STR_SETTINGSWINDOW_CAPTUREENABLE_HELP, (STRPTR)STR_SETTINGSWINDOW_CAPTUREENABLE_HELP_STR },
    { STR_SETTINGSWINDOW_CAPTUREDRAWER, (STRPTR)STR_SETTINGSWINDOW_CAPTUREDRAWER_STR },
    { STR_SETTINGSWINDOW_CAPTUREDRAWER_KEY, (STRPTR)STR_SETTINGSWINDOW_CAPTUREDRAWER_KEY_STR },
    { STR_SETTINGSWINDOW_CAPTUREDRAWER_HELP, (STRPTR)STR_SETTINGSWINDOW_CAPTUREDRAWER_HELP_STR },
    { STR_SETTINGSWINDOW_CAPTUREFILE, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFILE_STR },
    { STR_SETTINGSWINDOW_CAPTUREFILE_KEY, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFILE_KEY_STR },
    { STR_SETTINGSWINDOW_CAPTUREFILE_HELP, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFILE_HELP_STR },
    { STR_SETTINGSWINDOW_CAPTUREFORMAT, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFORMAT_STR },
    { STR_SETTINGSWINDOW_CAPTUREFORMAT_KEY, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFORMAT_KEY_STR },
    { STR_SETTINGSWINDOW_CAPTUREFORMAT_HELP, (STRPTR)STR_SETTINGSWINDOW_CAPTUREFORMAT_HELP_STR },
    { STR_SETTINGSWINDOW_FORMAT_JPG, (STRPTR)STR_SETTINGSWINDOW_FORMAT_JPG_STR },
    { STR_SETTINGSWINDOW_FORMAT_PNG, (STRPTR)STR_SETTINGSWINDOW_FORMAT_PNG_STR },
    { STR_SETTINGSWINDOW_UPLOAD, (STRPTR)STR_SETTINGSWINDOW_UPLOAD_STR },
    { STR_SETTINGSWINDOW_UPLOADENABLE, (STRPTR)STR_SETTINGSWINDOW_UPLOADENABLE_STR },
    { STR_SETTINGSWINDOW_UPLOADENABLE_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADENABLE_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADENABLE_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADENABLE_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADSERVER, (STRPTR)STR_SETTINGSWINDOW_UPLOADSERVER_STR },
    { STR_SETTINGSWINDOW_UPLOADSERVER_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADSERVER_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADSERVER_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADSERVER_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSIVE, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSIVE_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSIVE_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSIVE_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSIVE_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSIVE_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADTIMEOUT, (STRPTR)STR_SETTINGSWINDOW_UPLOADTIMEOUT_STR },
    { STR_SETTINGSWINDOW_UPLOADTIMEOUT_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADTIMEOUT_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADTIMEOUT_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADTIMEOUT_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADUSER, (STRPTR)STR_SETTINGSWINDOW_UPLOADUSER_STR },
    { STR_SETTINGSWINDOW_UPLOADUSER_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADUSER_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADUSER_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADUSER_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSWORD, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSWORD_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSWORD_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSWORD_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADPASSWORD_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADPASSWORD_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADDRAWER, (STRPTR)STR_SETTINGSWINDOW_UPLOADDRAWER_STR },
    { STR_SETTINGSWINDOW_UPLOADDRAWER_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADDRAWER_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADDRAWER_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADDRAWER_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADFILE, (STRPTR)STR_SETTINGSWINDOW_UPLOADFILE_STR },
    { STR_SETTINGSWINDOW_UPLOADFILE_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADFILE_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADFILE_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADFILE_HELP_STR },
    { STR_SETTINGSWINDOW_UPLOADFORMAT, (STRPTR)STR_SETTINGSWINDOW_UPLOADFORMAT_STR },
    { STR_SETTINGSWINDOW_UPLOADFORMAT_KEY, (STRPTR)STR_SETTINGSWINDOW_UPLOADFORMAT_KEY_STR },
    { STR_SETTINGSWINDOW_UPLOADFORMAT_HELP, (STRPTR)STR_SETTINGSWINDOW_UPLOADFORMAT_HELP_STR },
    { STR_SETTINGSWINDOW_LOG, (STRPTR)STR_SETTINGSWINDOW_LOG_STR },
    { STR_SETTINGSWINDOW_LOGLEVEL, (STRPTR)STR_SETTINGSWINDOW_LOGLEVEL_STR },
    { STR_SETTINGSWINDOW_LOGLEVEL_KEY, (STRPTR)STR_SETTINGSWINDOW_LOGLEVEL_KEY_STR },
    { STR_SETTINGSWINDOW_LOGLEVEL_HELP, (STRPTR)STR_SETTINGSWINDOW_LOGLEVEL_HELP_STR },
    { STR_LOGLEVEL_OFF, (STRPTR)STR_LOGLEVEL_OFF_STR },
    { STR_LOGLEVEL_FAILURE, (STRPTR)STR_LOGLEVEL_FAILURE_STR },
    { STR_LOGLEVEL_ERROR, (STRPTR)STR_LOGLEVEL_ERROR_STR },
    { STR_LOGLEVEL_WARNING, (STRPTR)STR_LOGLEVEL_WARNING_STR },
    { STR_LOGLEVEL_INFO, (STRPTR)STR_LOGLEVEL_INFO_STR },
    { STR_LOGLEVEL_DEBUG, (STRPTR)STR_LOGLEVEL_DEBUG_STR },
    { STR_SPECIFIER_YEAR_HELP, (STRPTR)STR_SPECIFIER_YEAR_HELP_STR },
    { STR_SPECIFIER_MONTH_HELP, (STRPTR)STR_SPECIFIER_MONTH_HELP_STR },
    { STR_SPECIFIER_DAY_HELP, (STRPTR)STR_SPECIFIER_DAY_HELP_STR },
    { STR_SPECIFIER_HOUR_HELP, (STRPTR)STR_SPECIFIER_HOUR_HELP_STR },
    { STR_SPECIFIER_MINUTE_HELP, (STRPTR)STR_SPECIFIER_MINUTE_HELP_STR },
    { STR_SPECIFIER_SECOND_HELP, (STRPTR)STR_SPECIFIER_SECOND_HELP_STR },
    { STR_SPECIFIER_COUNTER_HELP, (STRPTR)STR_SPECIFIER_COUNTER_HELP_STR },
    { STR_PROGRESS_TOGGLE, (STRPTR)STR_PROGRESS_TOGGLE_STR },
    { STR_PROGRESS_TOGGLE_KEY, (STRPTR)STR_PROGRESS_TOGGLE_KEY_STR },
    { STR_PROGRESS_TOGGLE_HELP, (STRPTR)STR_PROGRESS_TOGGLE_HELP_STR },
    { STR_PROGRESS_CANCEL, (STRPTR)STR_PROGRESS_CANCEL_STR },
    { STR_PROGRESS_CANCEL_KEY, (STRPTR)STR_PROGRESS_CANCEL_KEY_STR },
    { STR_PROGRESS_CANCEL_HELP, (STRPTR)STR_PROGRESS_CANCEL_HELP_STR },
};


#endif /* cAMIra_ARRAY */


/****************************************************************************/


#ifdef cAMIra_BLOCK

static const char cAMIra_Block[] =
{

     "\x00\x00\x00\x00" "\x00\x1a"
    STR_CAMIRA_DESCRIPTION_STR "\x00"
     "\x00\x00\x00\x01" "\x00\x28"
    STR_CAMIRA_TRANSLATION_BY_STR "\x00"
     "\x00\x00\x00\x02" "\x00\x06"
    STR_MAINWINDOW_TITLE_STR ""
     "\x00\x00\x00\x03" "\x00\x08"
    STR_MAINWINDOW_RELEASE_STR "\x00"
     "\x00\x00\x00\x04" "\x00\x02"
    STR_MAINWINDOW_RELEASE_KEY_STR "\x00"
     "\x00\x00\x00\x05" "\x00\x34"
    STR_MAINWINDOW_RELEASE_HELP_STR ""
     "\x00\x00\x00\x06" "\x00\x08"
    STR_MAINMENU_PROJECT_STR "\x00"
     "\x00\x00\x00\x07" "\x00\x0a"
    STR_MAINMENU_ABOUT_STR "\x00"
     "\x00\x00\x00\x08" "\x00\x02"
    STR_MAINMENU_ABOUT_KEY_STR "\x00"
     "\x00\x00\x00\x09" "\x00\x0e"
    STR_MAINMENU_ABOUTMUI_STR "\x00"
     "\x00\x00\x00\x0a" "\x00\x04"
    STR_MAINMENU_QUIT_STR ""
     "\x00\x00\x00\x0b" "\x00\x02"
    STR_MAINMENU_QUIT_KEY_STR "\x00"
     "\x00\x00\x00\x0c" "\x00\x04"
    STR_MAINMENU_VIEW_STR ""
     "\x00\x00\x00\x0d" "\x00\x0e"
    STR_MAINMENU_LOGWINDOW_STR ""
     "\x00\x00\x00\x0e" "\x00\x02"
    STR_MAINMENU_LOGWINDOW_KEY_STR "\x00"
     "\x00\x00\x00\x0f" "\x00\x08"
    STR_MAINMENU_SETTINGS_STR ""
     "\x00\x00\x00\x10" "\x00\x0a"
    STR_MAINMENU_SOURCE_STR ""
     "\x00\x00\x00\x11" "\x00\x02"
    STR_MAINMENU_SOURCE_KEY_STR "\x00"
     "\x00\x00\x00\x12" "\x00\x0a"
    STR_MAINMENU_STAMP_STR "\x00"
     "\x00\x00\x00\x13" "\x00\x02"
    STR_MAINMENU_STAMP_KEY_STR "\x00"
     "\x00\x00\x00\x14" "\x00\x0c"
    STR_MAINMENU_DISPLAY_STR "\x00"
     "\x00\x00\x00\x15" "\x00\x02"
    STR_MAINMENU_DISPLAY_KEY_STR "\x00"
     "\x00\x00\x00\x16" "\x00\x0e"
    STR_MAINMENU_SCHEDULER_STR "\x00"
     "\x00\x00\x00\x17" "\x00\x02"
    STR_MAINMENU_SCHEDULER_KEY_STR "\x00"
     "\x00\x00\x00\x18" "\x00\x0c"
    STR_MAINMENU_CAPTURE_STR "\x00"
     "\x00\x00\x00\x19" "\x00\x02"
    STR_MAINMENU_CAPTURE_KEY_STR "\x00"
     "\x00\x00\x00\x1a" "\x00\x0a"
    STR_MAINMENU_UPLOAD_STR ""
     "\x00\x00\x00\x1b" "\x00\x02"
    STR_MAINMENU_UPLOAD_KEY_STR "\x00"
     "\x00\x00\x00\x1c" "\x00\x08"
    STR_MAINMENU_LOG_STR "\x00"
     "\x00\x00\x00\x1d" "\x00\x02"
    STR_MAINMENU_LOG_KEY_STR "\x00"
     "\x00\x00\x00\x1e" "\x00\x08"
    STR_MAINMENU_MUI_STR "\x00"
     "\x00\x00\x00\x1f" "\x00\x12"
    STR_ABOUTWINDOW_TITLE_STR ""
     "\x00\x00\x00\x20" "\x00\x02"
    STR_ABOUTWINDOW_OK_STR ""
     "\x00\x00\x00\x21" "\x00\x02"
    STR_ABOUTWINDOW_OK_KEY_STR "\x00"
     "\x00\x00\x00\x22" "\x00\x38"
    STR_ABOUTWINDOW_OK_HELP_STR "\x00"
     "\x00\x00\x00\x23" "\x00\x0a"
    STR_LOGWINDOW_TITLE_STR ""
     "\x00\x00\x00\x24" "\x00\x06"
    STR_LOGWINDOW_CLOSE_STR "\x00"
     "\x00\x00\x00\x25" "\x00\x02"
    STR_LOGWINDOW_CLOSE_KEY_STR "\x00"
     "\x00\x00\x00\x26" "\x00\x24"
    STR_LOGWINDOW_CLOSE_HELP_STR "\x00"
     "\x00\x00\x00\x27" "\x00\x06"
    STR_LOGWINDOW_FLUSH_STR "\x00"
     "\x00\x00\x00\x28" "\x00\x02"
    STR_LOGWINDOW_FLUSH_KEY_STR "\x00"
     "\x00\x00\x00\x29" "\x00\x4c"
    STR_LOGWINDOW_FLUSH_HELP_STR ""
     "\x00\x00\x00\x2a" "\x00\x04"
    STR_LOGWINDOW_SAVE_STR ""
     "\x00\x00\x00\x2b" "\x00\x02"
    STR_LOGWINDOW_SAVE_KEY_STR "\x00"
     "\x00\x00\x00\x2c" "\x00\x3e"
    STR_LOGWINDOW_SAVE_HELP_STR ""
     "\x00\x00\x00\x2d" "\x00\x10"
    STR_SETTINGSWINDOW_TITLE_STR "\x00"
     "\x00\x00\x00\x2e" "\x00\x02"
    STR_SETTINGSWINDOW_OK_STR ""
     "\x00\x00\x00\x2f" "\x00\x02"
    STR_SETTINGSWINDOW_OK_KEY_STR "\x00"
     "\x00\x00\x00\x30" "\x00\x3a"
    STR_SETTINGSWINDOW_OK_HELP_STR "\x00"
     "\x00\x00\x00\x31" "\x00\x06"
    STR_SETTINGSWINDOW_CANCEL_STR ""
     "\x00\x00\x00\x32" "\x00\x02"
    STR_SETTINGSWINDOW_CANCEL_KEY_STR "\x00"
     "\x00\x00\x00\x33" "\x00\x4e"
    STR_SETTINGSWINDOW_CANCEL_HELP_STR "\x00"
     "\x00\x00\x00\x34" "\x00\x1c"
    STR_SETTINGSWINDOW_CATEGORYLIST_HELP_STR ""
     "\x00\x00\x00\x35" "\x00\x06"
    STR_SETTINGSWINDOW_SOURCE_STR ""
     "\x00\x00\x00\x36" "\x00\x06"
    STR_SETTINGSWINDOW_VHIDRIVER_STR ""
     "\x00\x00\x00\x37" "\x00\x02"
    STR_SETTINGSWINDOW_VHIDRIVER_KEY_STR "\x00"
     "\x00\x00\x00\x38" "\x00\x3a"
    STR_SETTINGSWINDOW_VHIDRIVER_HELP_STR "\x00"
     "\x00\x00\x00\x39" "\x00\x04"
    STR_SETTINGSWINDOW_VHIINFO_STR ""
     "\x00\x00\x00\x3a" "\x00\x1e"
    STR_SETTINGSWINDOW_VHIINFO_TEMPLATE_STR "\x00"
     "\x00\x00\x00\x3b" "\x00\x02"
    STR_SETTINGSWINDOW_VHIINFO_EMPTY_STR "\x00"
     "\x00\x00\x00\x3c" "\x00\x06"
    STR_SETTINGSWINDOW_VHIINPUT_STR "\x00"
     "\x00\x00\x00\x3d" "\x00\x02"
    STR_SETTINGSWINDOW_VHIINPUT_KEY_STR "\x00"
     "\x00\x00\x00\x3e" "\x00\x26"
    STR_SETTINGSWINDOW_VHIINPUT_HELP_STR ""
     "\x00\x00\x00\x3f" "\x00\x06"
    STR_SETTINGSWINDOW_VHIVIDEOFORMAT_STR ""
     "\x00\x00\x00\x40" "\x00\x02"
    STR_SETTINGSWINDOW_VHIVIDEOFORMAT_KEY_STR "\x00"
     "\x00\x00\x00\x41" "\x00\x28"
    STR_SETTINGSWINDOW_VHIVIDEOFORMAT_HELP_STR "\x00"
     "\x00\x00\x00\x42" "\x00\x06"
    STR_SETTINGSWINDOW_VHICOLOR_STR "\x00"
     "\x00\x00\x00\x43" "\x00\x02"
    STR_SETTINGSWINDOW_VHICOLOR_KEY_STR "\x00"
     "\x00\x00\x00\x44" "\x00\x28"
    STR_SETTINGSWINDOW_VHICOLOR_HELP_STR ""
     "\x00\x00\x00\x45" "\x00\x02"
    STR_SETTINGSWINDOW_VHIX1_STR ""
     "\x00\x00\x00\x46" "\x00\x02"
    STR_SETTINGSWINDOW_VHIX1_KEY_STR "\x00"
     "\x00\x00\x00\x47" "\x00\x44"
    STR_SETTINGSWINDOW_VHIX1_HELP_STR ""
     "\x00\x00\x00\x48" "\x00\x02"
    STR_SETTINGSWINDOW_VHIY1_STR ""
     "\x00\x00\x00\x49" "\x00\x02"
    STR_SETTINGSWINDOW_VHIY1_KEY_STR "\x00"
     "\x00\x00\x00\x4a" "\x00\x42"
    STR_SETTINGSWINDOW_VHIY1_HELP_STR ""
     "\x00\x00\x00\x4b" "\x00\x02"
    STR_SETTINGSWINDOW_VHIX2_STR ""
     "\x00\x00\x00\x4c" "\x00\x02"
    STR_SETTINGSWINDOW_VHIX2_KEY_STR "\x00"
     "\x00\x00\x00\x4d" "\x00\x46"
    STR_SETTINGSWINDOW_VHIX2_HELP_STR "\x00"
     "\x00\x00\x00\x4e" "\x00\x02"
    STR_SETTINGSWINDOW_VHIY2_STR ""
     "\x00\x00\x00\x4f" "\x00\x02"
    STR_SETTINGSWINDOW_VHIY2_KEY_STR "\x00"
     "\x00\x00\x00\x50" "\x00\x44"
    STR_SETTINGSWINDOW_VHIY2_HELP_STR "\x00"
     "\x00\x00\x00\x51" "\x00\x06"
    STR_SETTINGSWINDOW_VHIWIDTH_STR "\x00"
     "\x00\x00\x00\x52" "\x00\x02"
    STR_SETTINGSWINDOW_VHIWIDTH_KEY_STR "\x00"
     "\x00\x00\x00\x53" "\x00\x24"
    STR_SETTINGSWINDOW_VHIWIDTH_HELP_STR ""
     "\x00\x00\x00\x54" "\x00\x06"
    STR_SETTINGSWINDOW_VHIHEIGHT_STR ""
     "\x00\x00\x00\x55" "\x00\x02"
    STR_SETTINGSWINDOW_VHIHEIGHT_KEY_STR "\x00"
     "\x00\x00\x00\x56" "\x00\x26"
    STR_SETTINGSWINDOW_VHIHEIGHT_HELP_STR "\x00"
     "\x00\x00\x00\x57" "\x00\x06"
    STR_SETTINGSWINDOW_STAMP_STR "\x00"
     "\x00\x00\x00\x58" "\x00\x06"
    STR_SETTINGSWINDOW_STAMPENABLE_STR ""
     "\x00\x00\x00\x59" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPENABLE_KEY_STR "\x00"
     "\x00\x00\x00\x5a" "\x00\x44"
    STR_SETTINGSWINDOW_STAMPENABLE_HELP_STR "\x00"
     "\x00\x00\x00\x5b" "\x00\x04"
    STR_SETTINGSWINDOW_STAMPTEXT_STR ""
     "\x00\x00\x00\x5c" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPTEXT_KEY_STR "\x00"
     "\x00\x00\x00\x5d" "\x00\x8a"
    STR_SETTINGSWINDOW_STAMPTEXT_HELP_STR "\x00"
     "\x00\x00\x00\x5e" "\x00\x04"
    STR_SETTINGSWINDOW_STAMPFONT_STR ""
     "\x00\x00\x00\x5f" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPFONT_KEY_STR "\x00"
     "\x00\x00\x00\x60" "\x00\x50"
    STR_SETTINGSWINDOW_STAMPFONT_HELP_STR ""
     "\x00\x00\x00\x61" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPX_STR "\x00"
     "\x00\x00\x00\x62" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPX_KEY_STR "\x00"
     "\x00\x00\x00\x63" "\x00\x38"
    STR_SETTINGSWINDOW_STAMPX_HELP_STR "\x00"
     "\x00\x00\x00\x64" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPY_STR "\x00"
     "\x00\x00\x00\x65" "\x00\x02"
    STR_SETTINGSWINDOW_STAMPY_KEY_STR "\x00"
     "\x00\x00\x00\x66" "\x00\x36"
    STR_SETTINGSWINDOW_STAMPY_HELP_STR "\x00"
     "\x00\x00\x00\x67" "\x00\x08"
    STR_SETTINGSWINDOW_DISPLAY_STR "\x00"
     "\x00\x00\x00\x68" "\x00\x06"
    STR_SETTINGSWINDOW_DISPLAYENABLE_STR ""
     "\x00\x00\x00\x69" "\x00\x02"
    STR_SETTINGSWINDOW_DISPLAYENABLE_KEY_STR "\x00"
     "\x00\x00\x00\x6a" "\x00\x48"
    STR_SETTINGSWINDOW_DISPLAYENABLE_HELP_STR ""
     "\x00\x00\x00\x6b" "\x00\x0c"
    STR_SETTINGSWINDOW_DISPLAYINTERVAL_STR "\x00"
     "\x00\x00\x00\x6c" "\x00\x02"
    STR_SETTINGSWINDOW_DISPLAYINTERVAL_KEY_STR "\x00"
     "\x00\x00\x00\x6d" "\x00\xb2"
    STR_SETTINGSWINDOW_DISPLAYINTERVAL_HELP_STR ""
     "\x00\x00\x00\x6e" "\x00\x08"
    STR_SETTINGSWINDOW_DISPLAYZOOM_STR ""
     "\x00\x00\x00\x6f" "\x00\x02"
    STR_SETTINGSWINDOW_DISPLAYZOOM_KEY_STR "\x00"
     "\x00\x00\x00\x70" "\x00\x82"
    STR_SETTINGSWINDOW_DISPLAYZOOM_HELP_STR ""
     "\x00\x00\x00\x71" "\x00\x06"
    STR_SETTINGSWINDOW_DISPLAYRATIO_STR "\x00"
     "\x00\x00\x00\x72" "\x00\x02"
    STR_SETTINGSWINDOW_DISPLAYRATIO_KEY_STR "\x00"
     "\x00\x00\x00\x73" "\x00\x4e"
    STR_SETTINGSWINDOW_DISPLAYRATIO_HELP_STR ""
     "\x00\x00\x00\x74" "\x00\x04"
    STR_SETTINGSWINDOW_DISPLAYRATIOFREE_STR ""
     "\x00\x00\x00\x75" "\x00\x04"
    STR_SETTINGSWINDOW_DISPLAYRATIOKEEP_STR ""
     "\x00\x00\x00\x76" "\x00\x0a"
    STR_SETTINGSWINDOW_SCHEDULER_STR "\x00"
     "\x00\x00\x00\x77" "\x00\x0c"
    STR_SETTINGSWINDOW_SCHEDULERINTERVAL_STR ""
     "\x00\x00\x00\x78" "\x00\x02"
    STR_SETTINGSWINDOW_SCHEDULERINTERVAL_KEY_STR "\x00"
     "\x00\x00\x00\x79" "\x00\x6a"
    STR_SETTINGSWINDOW_SCHEDULERINTERVAL_HELP_STR ""
     "\x00\x00\x00\x7a" "\x00\x08"
    STR_SETTINGSWINDOW_CAPTURE_STR "\x00"
     "\x00\x00\x00\x7b" "\x00\x06"
    STR_SETTINGSWINDOW_CAPTUREENABLE_STR ""
     "\x00\x00\x00\x7c" "\x00\x02"
    STR_SETTINGSWINDOW_CAPTUREENABLE_KEY_STR "\x00"
     "\x00\x00\x00\x7d" "\x00\x58"
    STR_SETTINGSWINDOW_CAPTUREENABLE_HELP_STR ""
     "\x00\x00\x00\x7e" "\x00\x06"
    STR_SETTINGSWINDOW_CAPTUREDRAWER_STR ""
     "\x00\x00\x00\x7f" "\x00\x02"
    STR_SETTINGSWINDOW_CAPTUREDRAWER_KEY_STR "\x00"
     "\x00\x00\x00\x80" "\x00\x5a"
    STR_SETTINGSWINDOW_CAPTUREDRAWER_HELP_STR ""
     "\x00\x00\x00\x81" "\x00\x04"
    STR_SETTINGSWINDOW_CAPTUREFILE_STR ""
     "\x00\x00\x00\x82" "\x00\x02"
    STR_SETTINGSWINDOW_CAPTUREFILE_KEY_STR "\x00"
     "\x00\x00\x00\x83" "\x00\xca"
    STR_SETTINGSWINDOW_CAPTUREFILE_HELP_STR ""
     "\x00\x00\x00\x84" "\x00\x06"
    STR_SETTINGSWINDOW_CAPTUREFORMAT_STR ""
     "\x00\x00\x00\x85" "\x00\x02"
    STR_SETTINGSWINDOW_CAPTUREFORMAT_KEY_STR "\x00"
     "\x00\x00\x00\x86" "\x00\x32"
    STR_SETTINGSWINDOW_CAPTUREFORMAT_HELP_STR "\x00"
     "\x00\x00\x00\x87" "\x00\x04"
    STR_SETTINGSWINDOW_FORMAT_JPG_STR "\x00"
     "\x00\x00\x00\x88" "\x00\x04"
    STR_SETTINGSWINDOW_FORMAT_PNG_STR "\x00"
     "\x00\x00\x00\x89" "\x00\x06"
    STR_SETTINGSWINDOW_UPLOAD_STR ""
     "\x00\x00\x00\x8a" "\x00\x06"
    STR_SETTINGSWINDOW_UPLOADENABLE_STR ""
     "\x00\x00\x00\x8b" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADENABLE_KEY_STR "\x00"
     "\x00\x00\x00\x8c" "\x00\x62"
    STR_SETTINGSWINDOW_UPLOADENABLE_HELP_STR ""
     "\x00\x00\x00\x8d" "\x00\x06"
    STR_SETTINGSWINDOW_UPLOADSERVER_STR ""
     "\x00\x00\x00\x8e" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADSERVER_KEY_STR "\x00"
     "\x00\x00\x00\x8f" "\x00\x1c"
    STR_SETTINGSWINDOW_UPLOADSERVER_HELP_STR "\x00"
     "\x00\x00\x00\x90" "\x00\x08"
    STR_SETTINGSWINDOW_UPLOADPASSIVE_STR "\x00"
     "\x00\x00\x00\x91" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADPASSIVE_KEY_STR "\x00"
     "\x00\x00\x00\x92" "\x00\x64"
    STR_SETTINGSWINDOW_UPLOADPASSIVE_HELP_STR "\x00"
     "\x00\x00\x00\x93" "\x00\x0c"
    STR_SETTINGSWINDOW_UPLOADTIMEOUT_STR "\x00"
     "\x00\x00\x00\x94" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADTIMEOUT_KEY_STR "\x00"
     "\x00\x00\x00\x95" "\x00\x6c"
    STR_SETTINGSWINDOW_UPLOADTIMEOUT_HELP_STR ""
     "\x00\x00\x00\x96" "\x00\x04"
    STR_SETTINGSWINDOW_UPLOADUSER_STR ""
     "\x00\x00\x00\x97" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADUSER_KEY_STR "\x00"
     "\x00\x00\x00\x98" "\x00\x44"
    STR_SETTINGSWINDOW_UPLOADUSER_HELP_STR "\x00"
     "\x00\x00\x00\x99" "\x00\x08"
    STR_SETTINGSWINDOW_UPLOADPASSWORD_STR ""
     "\x00\x00\x00\x9a" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADPASSWORD_KEY_STR "\x00"
     "\x00\x00\x00\x9b" "\x00\x66"
    STR_SETTINGSWINDOW_UPLOADPASSWORD_HELP_STR ""
     "\x00\x00\x00\x9c" "\x00\x06"
    STR_SETTINGSWINDOW_UPLOADDRAWER_STR ""
     "\x00\x00\x00\x9d" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADDRAWER_KEY_STR "\x00"
     "\x00\x00\x00\x9e" "\x00\x8a"
    STR_SETTINGSWINDOW_UPLOADDRAWER_HELP_STR "\x00"
     "\x00\x00\x00\x9f" "\x00\x04"
    STR_SETTINGSWINDOW_UPLOADFILE_STR ""
     "\x00\x00\x00\xa0" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADFILE_KEY_STR "\x00"
     "\x00\x00\x00\xa1" "\x00\x40"
    STR_SETTINGSWINDOW_UPLOADFILE_HELP_STR ""
     "\x00\x00\x00\xa2" "\x00\x06"
    STR_SETTINGSWINDOW_UPLOADFORMAT_STR ""
     "\x00\x00\x00\xa3" "\x00\x02"
    STR_SETTINGSWINDOW_UPLOADFORMAT_KEY_STR "\x00"
     "\x00\x00\x00\xa4" "\x00\x30"
    STR_SETTINGSWINDOW_UPLOADFORMAT_HELP_STR ""
     "\x00\x00\x00\xa5" "\x00\x04"
    STR_SETTINGSWINDOW_LOG_STR "\x00"
     "\x00\x00\x00\xa6" "\x00\x06"
    STR_SETTINGSWINDOW_LOGLEVEL_STR "\x00"
     "\x00\x00\x00\xa7" "\x00\x02"
    STR_SETTINGSWINDOW_LOGLEVEL_KEY_STR "\x00"
     "\x00\x00\x00\xa8" "\x00\x40"
    STR_SETTINGSWINDOW_LOGLEVEL_HELP_STR ""
     "\x00\x00\x00\xa9" "\x00\x04"
    STR_LOGLEVEL_OFF_STR "\x00"
     "\x00\x00\x00\xaa" "\x00\x08"
    STR_LOGLEVEL_FAILURE_STR "\x00"
     "\x00\x00\x00\xab" "\x00\x06"
    STR_LOGLEVEL_ERROR_STR "\x00"
     "\x00\x00\x00\xac" "\x00\x08"
    STR_LOGLEVEL_WARNING_STR "\x00"
     "\x00\x00\x00\xad" "\x00\x04"
    STR_LOGLEVEL_INFO_STR ""
     "\x00\x00\x00\xae" "\x00\x06"
    STR_LOGLEVEL_DEBUG_STR "\x00"
     "\x00\x00\x00\xaf" "\x00\x04"
    STR_SPECIFIER_YEAR_HELP_STR ""
     "\x00\x00\x00\xb0" "\x00\x22"
    STR_SPECIFIER_MONTH_HELP_STR "\x00"
     "\x00\x00\x00\xb1" "\x00\x26"
    STR_SPECIFIER_DAY_HELP_STR "\x00"
     "\x00\x00\x00\xb2" "\x00\x1a"
    STR_SPECIFIER_HOUR_HELP_STR ""
     "\x00\x00\x00\xb3" "\x00\x0e"
    STR_SPECIFIER_MINUTE_HELP_STR ""
     "\x00\x00\x00\xb4" "\x00\x0e"
    STR_SPECIFIER_SECOND_HELP_STR ""
     "\x00\x00\x00\xb5" "\x00\x1a"
    STR_SPECIFIER_COUNTER_HELP_STR ""
     "\x00\x00\x00\xb6" "\x00\x02"
    STR_PROGRESS_TOGGLE_STR "\x00"
     "\x00\x00\x00\xb7" "\x00\x02"
    STR_PROGRESS_TOGGLE_KEY_STR "\x00"
     "\x00\x00\x00\xb8" "\x00\x58"
    STR_PROGRESS_TOGGLE_HELP_STR "\x00"
     "\x00\x00\x00\xb9" "\x00\x02"
    STR_PROGRESS_CANCEL_STR "\x00"
     "\x00\x00\x00\xba" "\x00\x02"
    STR_PROGRESS_CANCEL_KEY_STR "\x00"
     "\x00\x00\x00\xbb" "\x00\x34"
    STR_PROGRESS_CANCEL_HELP_STR ""

};

#endif /* cAMIra_BLOCK */


/****************************************************************************/


#ifdef cAMIra_CODE

#ifndef cAMIra_CODE_EXISTS
 #define cAMIra_CODE_EXISTS

 STRPTR GetcAMIraString(struct cAMIra_LocaleInfo *li, LONG stringNum)
 {
 LONG   *l;
 UWORD  *w;
 STRPTR  builtIn;

     l = (LONG *)cAMIra_Block;

     while (*l != stringNum)
       {
       w = (UWORD *)((ULONG)l + 4);
       l = (LONG *)((ULONG)l + (ULONG)*w + 6);
       }
     builtIn = (STRPTR)((ULONG)l + 6);

// #define cAMIra_XLocaleBase LocaleBase
// #define LocaleBase li->li_LocaleBase
    
     if(LocaleBase && li)
        return(GetCatalogStr(li->li_Catalog, stringNum, builtIn));

// #undef  LocaleBase
// #define LocaleBase XLocaleBase
// #undef  cAMIra_XLocaleBase

     return(builtIn);
 }

#else

 STRPTR GetcAMIraString(struct cAMIra_LocaleInfo *li, LONG stringNum);

#endif /* cAMIra_CODE_EXISTS */

#endif /* cAMIra_CODE */


/****************************************************************************/


#endif /* cAMIra_STRINGS_H */
